### ISSUE TITLE
Assert and meta fixes

### ISSUE THREAD

**Issue by lucteo** [Sparrow-lang/sparrow#22]
Make sure assert works properly.

- [x] make sure that implicit lib contains basic meta abstractions:
  - AstNode (or a simplified version of it)
  - astEval
  - lift
- [x] fix the existing assert -- make sure it can be used in the tests
- [ ] fix precedenceUtils -- similar problem to the asserts
- [ ] make it possible to have a direct mapping from Sparrow functions directly to Sparrow Ast nodes
  - e.g., `ife` can be directly mapped with ConditionalExp
- [x] compiler defines as usings
  - add standard defines into the compilation (e.g., compiler, OS, etc.)
  - allow user to provide his own defines; e.g.:
    - `-DDEBUG` produces `using DEBUG=1;`
    - `-DVERSION=2` produces `using VERSION=2;`
    - `-D'MYMACRO=compute(2)'` produces `using MYMACRO=compute(2);`
  - needed to properly turn on asserts
- [ ] add more assert-like functionality
  - enable assert to take an optional message as argument
  - add `assertEq`, `assertNe`, ...
- [x] add optional message to assert

**Comment by lucteo** [comment]
Fixed with #27

For the following Sparrow code:
    var a = 12;
    var b = 13;
    var c = 5;
    var foo: FooType = 10;
    assert(a == b);
    assert(a+1 < b);
    assert(a >= b, "intentional error");
    assert(foo._data == 100, "non-printable vars work too");
    assert(fact(c) != 120, "calling functions");

If compiled with DEBUG flag (include "-D DEBUG" in command line for the compiler), we get the following:
AssertTest.spr(44): assertion failure: check a[=12] == b[=13] has failed
AssertTest.spr(45): assertion failure: check a[=12]+1 < b[=13] has failed
AssertTest.spr(46): assertion failure: check a[=12] >= b[=13] has failed: intentional error
AssertTest.spr(47): assertion failure: check foo._data == 100 has failed: non-printable vars work too
AssertTest.spr(48): assertion failure: check fact(c[=5]) != 120 has failed: calling functions

We print the values of all (printable) variables.
